routes/frontend.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', 'HomeController@index')->name('frontend.index');
Route::get('/team', 'HomeController@team')->name('frontend.team');
Route::get('/match', 'MatchController@index')->name('frontend.match');
Route::get('/news', 'NewsController@news')->name('frontend.news');
Route::get('/news/{id}/detail', 'NewsController@detail')->name('frontend.news_detail');
Route::get('about', 'HomeController@about')->name('frontend.about');
Route::get('contact', 'ContactController@contact')->name('frontend.contact');
Route::post('contact/store', 'ContactController@store')->name('frontend.contact.store');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['namespace' => 'App\Http\Controllers\Backend', 'middleware' => 'auth'],function(){
    /* Dashboard */
    Route::get('/', function () {
        return view('backend.dashboard');
    });
    Route::get('dashboard', function () {
        return view('backend.dashboard');
    })->name('dashboard');

//    Route::get('profile', function () {
//        return view('auth.profile');
//    })->name('profile');


    Route::resource('site-setting', 'SiteSettingController');

    Route::resource('service', 'ServiceController');

    Route::resource('about', 'AboutController');

    Route::resource('contact', 'ContactController');

    Route::resource('progress', 'ProgressController');

    Route::resource('image_slider', 'ImageSliderController');

    Route::resource('news', 'NewsController');

    Route::resource('gallery', 'GalleryController');

    Route::resource('team', 'TeamController');

    Route::resource('player_role', 'PlayerRoleController');

    Route::resource('opponent_team', 'OpponentTeamController');

    Route::resource('match_fixture', 'MatchFixtureController');

    Route::get('/store-goals/{id}', [\App\Http\Controllers\Backend\MatchFixtureController::class, 'storeGoals'])->name('match.store_goals');

    Route::resource('fixture_table', 'FixtureTableController');

//    Route::post('/maintenance','AuthController@maintenanceMode')->name('maintenance');
//
//    Route::post('update-profile','AuthController@updateProfile')->name('auth.update-profile');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Http/Controllers/Backend/AboutController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\AboutRequest;
use App\Models\About;
use Illuminate\Http\Request;

class AboutController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $edit = About::first();
        return view('backend.about', compact('edit'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AboutRequest $request)
    {
        $edit = About::first();
        if ($edit){
            $edit->update($request->all());
        }else{
            About::create($request->all());
        }
        return redirect()->route('about.index')->withMsg('About has been updated successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/ContactController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Contact;
use Illuminate\Http\Request;

class ContactController extends Controller
{
    public function index(){
        $contacts = Contact::latest()->get();
        return view('backend.contact', compact('contacts'));
    }

    public function destroy(Contact $contact){
        $contact->delete();
        return redirect()->route('contact.index')->withMsg('Contact has been deleted successfully.');
    }
}

app/Http/Controllers/Backend/FixtureTableController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\FixtureTableRequest;
use App\Models\FixtureTable;
use App\Models\MatchFixture;
use App\Models\OpponentTeam;
use App\Models\SiteSetting;
use Illuminate\Http\Request;

class FixtureTableController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $siteSetting = SiteSetting::first();
        $fixtureTables = FixtureTable::orderBy('points', 'desc')->get();
        $ourTable[0] = (new MatchFixture())->ownStats();
        $fixtureTables =  collect($ourTable)->merge($fixtureTables)->sortByDesc('points');
        return view('backend.fixture_table.index', compact('fixtureTables', 'siteSetting'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $opponentTeams = OpponentTeam::where('status', 1)->get();
        return view('backend.fixture_table.create', compact('opponentTeams'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(FixtureTableRequest $request)
    {
        $request['matches_played'] = $request->wins + $request->draws + $request->losses;
        FixtureTable::create($request->all());
        return redirect()->route('fixture_table.index')->withMsg('Team added to fixture table successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(FixtureTable $fixtureTable)
    {
        $opponentTeams = OpponentTeam::where('status', 1)->get();
        return view('backend.fixture_table.create', compact('fixtureTable', 'opponentTeams'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(FixtureTableRequest $request, FixtureTable $fixtureTable)
    {
        $fixtureTable->update($request->all());
        return redirect()->route('fixture_table.index')->withMsg('Team updated to fixture table successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(FixtureTable $fixtureTable)
    {
        $fixtureTable->delete();
        return redirect()->route('fixture_table.index')->withMsg('Team deleted from fixture table successfully');
    }
}

app/Http/Controllers/Backend/GalleryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\GalleryRequest;
use App\Models\Gallery;
use Illuminate\Http\Request;

class GalleryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $galleries = Gallery::latest()->get();
        return view('backend.gallery.index', compact('galleries'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.gallery.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(GalleryRequest $request)
    {
        dd($request->all());
        $gallery = Gallery::create($request->all());
        if ($request->hasFile('image')){
            $gallery->addMedia($request->file('image'))->toMediaCollection();
        }
        return redirect()->route('gallery.index')->withMsg('Your Gallery has been successfully created.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/ImageSliderController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\ImageSliderRequest;
use App\Models\ImageSlider;
use Illuminate\Http\Request;

class ImageSliderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $imageSliders = ImageSlider::latest()->get();
        return view('backend.image_slider.index', compact('imageSliders'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.image_slider.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ImageSliderRequest $request)
    {
        $imageSlider = ImageSlider::create($request->all());
        if ($request->hasFile('image')){
            $imageSlider->addMedia($request->file('image'))->toMediaCollection();
        }
        return redirect()->route('image_slider.index')->withMsg('Your Image Slider has been successfully created.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(ImageSlider $imageSlider)
    {
        return view('backend.image_slider.create', compact('imageSlider'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ImageSliderRequest $request, ImageSlider $imageSlider)
    {
        if ($request->hasFile('image')){
            $imageSlider->clearMediaCollection();
            $imageSlider->addMedia($request->file('image'))->toMediaCollection();
        }
        $imageSlider->update($request->all());
        return redirect()->route('image_slider.index')->withMsg('Your Image Slider has been successfully updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(ImageSlider $imageSlider)
    {
        if ($imageSlider->hasMedia()){
            $imageSlider->clearMediaCollection();
        }
        $imageSlider->delete();
        return redirect()->route('image_slider.index')->withMsg('Your Image Slider has been successfully deleted.');
    }
}

app/Http/Controllers/Backend/MatchFixtureController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\MatchRequest;
use App\Models\MatchFixture;
use App\Models\OpponentTeam;
use App\Models\SiteSetting;
use Illuminate\Http\Request;

class MatchFixtureController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $siteSetting = SiteSetting::first();
        $opponentTeams = OpponentTeam::where('status', 1)->get();
        $matchFixtures = MatchFixture::latest()->get();
        return view('backend.match.index', compact('matchFixtures', 'opponentTeams', 'siteSetting'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $opponentTeams = OpponentTeam::where('status', 1)->get();
        return view('backend.match.create', compact('opponentTeams'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(MatchRequest $request)
    {
        MatchFixture::create($request->all());
        return redirect()->route('match_fixture.index')->withMsg('Your match fixture has been successfully created.');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit(MatchFixture $matchFixture)
    {
        $opponentTeams = OpponentTeam::where('status', 1)->get();
        return view('backend.match.create', compact('matchFixture', 'opponentTeams'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(MatchRequest $request, MatchFixture $matchFixture)
    {
        $matchFixture->update($request->all());
        return redirect()->route('match_fixture.index')->withMsg('Your match fixture has been successfully updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(MatchFixture $matchFixture)
    {
        $matchFixture->delete();
        return redirect()->route('match_fixture.index')->withMsg('Your match fixture has been successfully deleted.');
    }

    public function storeGoals(Request $request, $id)
    {
        $match = MatchFixture::find($id);
        $scored = $request->goal_scored;
        $conceded = $request->goal_conceded;
        $data = [
            'goal_scored' => $request->goal_scored,
            'goal_conceded' => $request->goal_conceded,
            'status' => 1,
        ];
        if ($scored > $conceded) {
            $data['result'] =  "wins";
        } elseif ($scored < $conceded) {
            $data['result'] =  "losses";
        } elseif ($scored == $conceded) {
            $data['result'] = "draws";
        } else {
            return abort(404, 'Matches Not Played');
        };
        $match->fill($data);
        $match->save();
        return response(json_encode($match));
    }
}

resources/views/backend/layouts/sidebar.blade.php
<!-- Main Sidebar -->
<?php //
//  $maintenance = Cache::get('maintenance') ?? 'off';
//?>
<aside class="main-sidebar col-12 col-md-3 col-lg-2 px-0">
    <div class="main-navbar">
        <nav class="navbar align-items-stretch navbar-light bg-white flex-md-nowrap border-bottom p-0">
            <a class="navbar-brand w-100 mr-0" href="{{route('dashboard')}}" style="line-height: 25px;">
                <div class="d-table m-auto">
                    {{--          <img id="main-logo" class="d-inline-block align-top mr-1" style="max-width: 25px;" src="{{asset('images/shards-dashboards-logo.svg')}}" alt="Shards Dashboard">--}}
                    <span class="d-none d-md-inline ml-1">{{config('app.name')}} Dashboard</span>
                </div>
            </a>
            <a class="toggle-sidebar d-sm-inline d-md-none d-lg-none">
                <i class="material-icons">&#xE5C4;</i>
            </a>
        </nav>
    </div>
    <form action="#" class="main-sidebar__search w-100 border-right d-sm-flex d-md-none d-lg-none">
        <div class="input-group input-group-seamless ml-3">
            <div class="input-group-prepend">
                <div class="input-group-text">
                    <i class="fas fa-search"></i>
                </div>
            </div>
            <input class="navbar-search form-control" type="text" placeholder="Search for something..."
                   aria-label="Search"></div>
    </form>

    {{--  <div class="row p-3">--}}
    {{--    <label id="labelMaintenance" for="maintenance" class="mx-auto">Maintenance Mode</label>--}}
    {{--    <div class="custom-control custom-switch ml-auto">--}}
    {{--        <input type="checkbox" class="custom-control-input" id="maintenance" onclick="$('#maintenanceForm').submit()" {{ $maintenance=='on'?'Checked':'' }}>--}}
    {{--        <label class="custom-control-label" onclick="$('#labelMaintenance').click()"></label>--}}
    {{--    </div>--}}
    {{--</div>--}}
    {{--<form id="maintenanceForm" action="#" method="post">--}}
    {{--    @csrf--}}
    {{--</form>--}}
    <div class="nav-wrapper accordion" id="accordionExample">
        <ul class="nav flex-column">
            <li class="nav-item">
                <a class="nav-link" href="{{route('dashboard')}}">
                    <i class="material-icons">edit</i>
                    <span>Dashboard</span>
                </a>
            </li>
            <!-- <li class="nav-item">
              <a class="nav-link " href="components-blog-posts.html">
                <i class="material-icons">vertical_split</i>
                <span>Blog Posts</span>
              </a>
            </li> -->

            <div class="nav-item has-child">
                <div class="card-header p-0 m-0" id="headingTwo">
                    <div class="nav-link collapsed d-flex align-items-center" data-toggle="collapse"
                         data-target="#collapseTwo"
                         aria-expanded="false" aria-controls="collapseTwo">
                        <i class="material-icons">note_add</i>
                        <span> Settings</span>
                        <i class="fa fa-plus ml-auto"></i>
                    </div>
                </div>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
                    <div class="card-body p-0">
                        <a class="nav-link p-2 pl-5" href="{{route('site-setting.index')}}">
                            <i class="material-icons">note_add</i>
                            <span>Site Settings</span>
                        </a>
                        {{--                <a class="nav-link p-2 pl-5" href="#">--}}
                        {{--                    <i class="material-icons">note_add</i>--}}
                        {{--                    <span>Main News Setting</span>--}}
                        {{--                </a>--}}

                        {{--                <a class="nav-link p-2 pl-5" href="#">--}}
                        {{--                    <i class="material-icons">note_add</i>--}}
                        {{--                    <span>Add Province</span>--}}
                        {{--                </a>--}}
                        {{--              <a class="nav-link p-2 pl-5" href="#">--}}
                        {{--                <i class="material-icons">note_add</i>--}}
                        {{--                <span>Image Slider</span>--}}
                        {{--              </a>--}}
                        {{--              <a class="nav-link p-2 pl-5" href="#">--}}
                        {{--                <i class="material-icons">note_add</i>--}}
                        {{--                <span>Useful Links</span>--}}
                        {{--              </a>--}}
                        {{--              <a class="nav-link p-2 pl-5" href="#">--}}
                        {{--                <i class="material-icons">note_add</i>--}}
                        {{--                <span>Social Media Links</span>--}}
                        {{--              </a>--}}
                        {{--              <a class="nav-link p-2 pl-5" href="#">--}}
                        {{--                <i class="material-icons">note_add</i>--}}
                        {{--                <span>Requested Contacts</span>--}}
                        {{--              </a>--}}
                    </div>
                </div>
            </div>

            <div class="nav-item has-child">
                <div class="card-header p-0 m-0" id="heading4">
                    <div class="nav-link collapsed d-flex align-items-center" data-toggle="collapse"
                         data-target="#collapse4"
                         aria-expanded="false" aria-controls="collapseTwo">
                        <i class="material-icons">note_add</i>
                        <span>Image Slider Setup</span>
                        <i class="fa fa-plus ml-auto"></i>
                    </div>
                </div>
                <div id="collapse4" class="collapse" aria-labelledby="heading4" data-parent="#accordionExample">
                    <div class="card-body p-0">
                        <a class="nav-link p-2 pl-5" href="{{route('image_slider.create')}}">
                            <i class="material-icons">note_add</i>
                            <span>Add Image Slider</span>
                        </a>
                        <a class="nav-link p-2 pl-5" href="{{route('image_slider.index')}}">
                            <i class="material-icons">note_add</i>
                            <span>Image Slider List</span>
                        </a>
                    </div>
                </div>
            </div>

            <div class="nav-item has-child">
                <div class="card-header p-0 m-0" id="heading7">
                    <div class="nav-link collapsed d-flex align-items-center" data-toggle="collapse"
                         data-target="#collapse7"
                         aria-expanded="false" aria-controls="collapseTwo">
                        <i class="material-icons">note_add</i>
                        <span>Team Setup</span>
                        <i class="fa fa-plus ml-auto"></i>
                    </div>
                </div>
                <div id="collapse7" class="collapse" aria-labelledby="heading7" data-parent="#accordionExample">
                    <div class="card-body p-0">
                        <a class="nav-link p-2 pl-5" href="{{route('player_role.index')}}">
                            <i class="material-icons">note_add</i>
                            <span>Player Positions</span>
                        </a>
                        <a class="nav-link p-2 pl-5" href="{{route('team.create')}}">
                            <i class="material-icons">note_add</i>
                            <span>Add Player</span>
                        </a>
                        <a class="nav-link p-2 pl-5" href="{{route('team.index')}}">
                            <i class="material-icons">note_add</i>
                            <span>Player List</span>
                        </a>
                        <a class="nav-link p-2 pl-5" href="{{route('opponent_team.index')}}">
                            <i class="material-icons">note_add</i>
                            <span>Opponent Team</span>
                        </a>
                    </div>
                </div>
            </div>


            <div class="nav-item has-child">
                <div class="card-header p-0 m-0" id="heading8">
                    <div class="nav-link collapsed d-flex align-items-center" data-toggle="collapse"
                         data-target="#collapse8"
                         aria-expanded="false" aria-controls="collapseTwo">
                        <i class="material-icons">note_add</i>
                        <span>Match Fixtures</span>
                        <i class="fa fa-plus ml-auto"></i>
                    </div>
                </div>
                <div id="collapse8" class="collapse" aria-labelledby="heading8" data-parent="#accordionExample">
                    <div class="card-body p-0">

                        <a class="nav-link p-2 pl-5" href="{{route('match_fixture.index')}}">
                            <i class="material-icons">note_add</i>
                            <span>Match Fixture</span>
                        </a>
                    </div>
                </div>
            </div>
            <div class="nav-item has-child">
                <div class="card-header p-0 m-0" id="heading9">
                    <div class="nav-link collapsed d-flex align-items-center" data-toggle="collapse"
                         data-target="#collapse9"
                         aria-expanded="false" aria-controls="collapseTwo">
                        <i class="material-icons">note_add</i>
                        <span>Table Section</span>
                        <i class="fa fa-plus ml-auto"></i>
                    </div>
                </div>
                <div id="collapse9" class="collapse" aria-labelledby="heading9" data-parent="#accordionExample">
                    <div class="card-body p-0">
                        <a class="nav-link p-2 pl-5" href="{{route('fixture_table.create')}}">
                            <i class="material-icons">note_add</i>
                            <span>Add Team in Table</span>
                        </a>
                        <a class="nav-link p-2 pl-5" href="{{route('fixture_table.index')}}">
                            <i class="material-icons">note_add</i>
                            <span>Table</span>
                        </a>
                    </div>
                </div>
            </div>

            <div class="nav-item has-child">
                <div class="card-header p-0 m-0" id="heading6">
                    <div class="nav-link collapsed d-flex align-items-center" data-toggle="collapse"
                         data-target="#collapse6"
                         aria-expanded="false" aria-controls="collapseTwo">
                        <i class="material-icons">note_add</i>
                        <span>Gallery Setup</span>
                        <i class="fa fa-plus ml-auto"></i>
                    </div>
                </div>
                <div id="collapse6" class="collapse" aria-labelledby="heading6" data-parent="#accordionExample">
                    <div class="card-body p-0">
                        <a class="nav-link p-2 pl-5" href="{{route('gallery.create')}}">
                            <i class="material-icons">note_add</i>
                            <span>Add Gallery</span>
                        </a>
                        <a class="nav-link p-2 pl-5" href="{{route('gallery.index')}}">
                            <i class="material-icons">note_add</i>
                            <span>Gallery List</span>
                        </a>
                    </div>
                </div>
            </div>

            <div class="nav-item has-child">
                <div class="card-header p-0 m-0" id="heading5">
                    <div class="nav-link collapsed d-flex align-items-center" data-toggle="collapse"
                         data-target="#collapse5"
                         aria-expanded="false" aria-controls="collapseTwo">
                        <i class="material-icons">note_add</i>
                        <span>News Setup</span>
                        <i class="fa fa-plus ml-auto"></i>
                    </div>
                </div>
                <div id="collapse5" class="collapse" aria-labelledby="heading5" data-parent="#accordionExample">
                    <div class="card-body p-0">
                        <a class="nav-link p-2 pl-5" href="{{route('news.create')}}">
                            <i class="material-icons">note_add</i>
                            <span>Add News</span>
                        </a>
                        <a class="nav-link p-2 pl-5" href="{{route('news.index')}}">
                            <i class="material-icons">note_add</i>
                            <span>News List</span>
                        </a>
                    </div>
                </div>
            </div>

            <li class="nav-item">
                <a class="nav-link " href="{{route('about.index')}}">
                    <i class="material-icons">note_add</i>
                    <span>About Page</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="{{route('contact.index')}}">
                    <i class="material-icons">note_add</i>
                    <span>Contact Page</span>
                </a>
            </li>

        </ul>
    </div>
</aside>