routes/frontend.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', 'HomeController@index')->name('frontend.index');
Route::get('/team', 'HomeController@team')->name('frontend.team');
Route::get('/match', 'MatchController@index')->name('frontend.match');
Route::get('/news', 'NewsController@news')->name('frontend.news');
Route::get('/news/{id}/detail', 'NewsController@detail')->name('frontend.news_detail');
Route::get('about', 'HomeController@about')->name('frontend.about');
Route::get('contact', 'ContactController@contact')->name('frontend.contact');
Route::post('contact/store', 'ContactController@store')->name('frontend.contact.store');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['namespace' => 'App\Http\Controllers\Backend', 'middleware' => 'auth'],function(){
    /* Dashboard */
    Route::get('/', function () {
        return view('backend.dashboard');
    });
    Route::get('dashboard', function () {
        return view('backend.dashboard');
    })->name('dashboard');

//    Route::get('profile', function () {
//        return view('auth.profile');
//    })->name('profile');


    Route::resource('site-setting', 'SiteSettingController');

    Route::resource('service', 'ServiceController');

    Route::resource('about', 'AboutController');

    Route::resource('contact', 'ContactController');

    Route::resource('progress', 'ProgressController');

    Route::resource('image_slider', 'ImageSliderController');

    Route::resource('news', 'NewsController');

    Route::resource('gallery', 'GalleryController');

    Route::resource('team', 'TeamController');

    Route::resource('player_role', 'PlayerRoleController');

    Route::resource('opponent_team', 'OpponentTeamController');

    Route::resource('match_fixture', 'MatchFixtureController');

    Route::get('/store-goals/{id}', [\App\Http\Controllers\Backend\MatchFixtureController::class, 'storeGoals'])->name('match.store_goals');

    Route::resource('fixture_table', 'FixtureTableController');

//    Route::post('/maintenance','AuthController@maintenanceMode')->name('maintenance');
//
//    Route::post('update-profile','AuthController@updateProfile')->name('auth.update-profile');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Http/Controllers/Backend/AboutController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\AboutRequest;
use App\Models\About;
use Illuminate\Http\Request;

class AboutController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $edit = About::first();
        return view('backend.about', compact('edit'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AboutRequest $request)
    {
        $edit = About::first();
        if ($edit){
            $edit->update($request->all());
        }else{
            About::create($request->all());
        }
        return redirect()->route('about.index')->withMsg('About has been updated successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/ContactController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Contact;
use Illuminate\Http\Request;

class ContactController extends Controller
{
    public function index(){
        $contacts = Contact::latest()->get();
        return view('backend.contact', compact('contacts'));
    }

    public function destroy(Contact $contact){
        $contact->delete();
        return redirect()->route('contact.index')->withMsg('Contact has been deleted successfully.');
    }
}

app/Http/Controllers/Backend/FixtureTableController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\FixtureTableRequest;
use App\Models\FixtureTable;
use App\Models\MatchFixture;
use App\Models\OpponentTeam;
use App\Models\SiteSetting;
use Illuminate\Http\Request;

class FixtureTableController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $siteSetting = SiteSetting::first();
        $fixtureTables = FixtureTable::orderBy('points', 'desc')->get();
        $ourTable[0] = (new MatchFixture())->ownStats();
        $fixtureTables =  collect($ourTable)->merge($fixtureTables)->sortByDesc('points');
        return view('backend.fixture_table.index', compact('fixtureTables', 'siteSetting'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $opponentTeams = OpponentTeam::where('status', 1)->get();
        return view('backend.fixture_table.create', compact('opponentTeams'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(FixtureTableRequest $request)
    {
        $request['matches_played'] = $request->wins + $request->draws + $request->losses;
        FixtureTable::create($request->all());
        return redirect()->route('fixture_table.index')->withMsg('Team added to fixture table successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(FixtureTable $fixtureTable)
    {
        $opponentTeams = OpponentTeam::where('status', 1)->get();
        return view('backend.fixture_table.create', compact('fixtureTable', 'opponentTeams'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(FixtureTableRequest $request, FixtureTable $fixtureTable)
    {
        $fixtureTable->update($request->all());
        return redirect()->route('fixture_table.index')->withMsg('Team updated to fixture table successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(FixtureTable $fixtureTable)
    {
        $fixtureTable->delete();
        return redirect()->route('fixture_table.index')->withMsg('Team deleted from fixture table successfully');
    }
}

app/Http/Controllers/Backend/GalleryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\GalleryRequest;
use App\Models\Gallery;
use Illuminate\Http\Request;

class GalleryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $galleries = Gallery::latest()->get();
        return view('backend.gallery.index', compact('galleries'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.gallery.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(GalleryRequest $request)
    {
        dd($request->all());
        $gallery = Gallery::create($request->all());
        if ($request->hasFile('image')){
            $gallery->addMedia($request->file('image'))->toMediaCollection();
        }
        return redirect()->route('gallery.index')->withMsg('Your Gallery has been successfully created.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/ImageSliderController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\ImageSliderRequest;
use App\Models\ImageSlider;
use Illuminate\Http\Request;

class ImageSliderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $imageSliders = ImageSlider::latest()->get();
        return view('backend.image_slider.index', compact('imageSliders'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.image_slider.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ImageSliderRequest $request)
    {
        $imageSlider = ImageSlider::create($request->all());
        if ($request->hasFile('image')){
            $imageSlider->addMedia($request->file('image'))->toMediaCollection();
        }
        return redirect()->route('image_slider.index')->withMsg('Your Image Slider has been successfully created.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(ImageSlider $imageSlider)
    {
        return view('backend.image_slider.create', compact('imageSlider'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ImageSliderRequest $request, ImageSlider $imageSlider)
    {
        if ($request->hasFile('image')){
            $imageSlider->clearMediaCollection();
            $imageSlider->addMedia($request->file('image'))->toMediaCollection();
        }
        $imageSlider->update($request->all());
        return redirect()->route('image_slider.index')->withMsg('Your Image Slider has been successfully updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(ImageSlider $imageSlider)
    {
        if ($imageSlider->hasMedia()){
            $imageSlider->clearMediaCollection();
        }
        $imageSlider->delete();
        return redirect()->route('image_slider.index')->withMsg('Your Image Slider has been successfully deleted.');
    }
}

app/Http/Controllers/Backend/MatchFixtureController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\MatchRequest;
use App\Models\MatchFixture;
use App\Models\OpponentTeam;
use App\Models\SiteSetting;
use Illuminate\Http\Request;

class MatchFixtureController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $siteSetting = SiteSetting::first();
        $opponentTeams = OpponentTeam::where('status', 1)->get();
        $matchFixtures = MatchFixture::latest()->get();
        return view('backend.match.index', compact('matchFixtures', 'opponentTeams', 'siteSetting'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $opponentTeams = OpponentTeam::where('status', 1)->get();
        return view('backend.match.create', compact('opponentTeams'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(MatchRequest $request)
    {
        MatchFixture::create($request->all());
        return redirect()->route('match_fixture.index')->withMsg('Your match fixture has been successfully created.');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit(MatchFixture $matchFixture)
    {
        $opponentTeams = OpponentTeam::where('status', 1)->get();
        return view('backend.match.create', compact('matchFixture', 'opponentTeams'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(MatchRequest $request, MatchFixture $matchFixture)
    {
        $matchFixture->update($request->all());
        return redirect()->route('match_fixture.index')->withMsg('Your match fixture has been successfully updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(MatchFixture $matchFixture)
    {
        $matchFixture->delete();
        return redirect()->route('match_fixture.index')->withMsg('Your match fixture has been successfully deleted.');
    }

    public function storeGoals(Request $request, $id)
    {
        $match = MatchFixture::find($id);
        $scored = $request->goal_scored;
        $conceded = $request->goal_conceded;
        $data = [
            'goal_scored' => $request->goal_scored,
            'goal_conceded' => $request->goal_conceded,
            'status' => 1,
        ];
        if ($scored > $conceded) {
            $data['result'] =  "wins";
        } elseif ($scored < $conceded) {
            $data['result'] =  "losses";
        } elseif ($scored == $conceded) {
            $data['result'] = "draws";
        } else {
            return abort(404, 'Matches Not Played');
        };
        $match->fill($data);
        $match->save();
        return response(json_encode($match));
    }
}

app/Http/Controllers/Frontend/NewsController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\News;

class NewsController extends Controller
{
    public function news(){
        $newses=News::where('status', 1)->get();
        $latestNews=News::where('status', 1)->latest()->take(4)->get();
        return view('frontend.news', compact('newses','latestNews'));
    }

    public function detail($id){
        $newsDetail = News::find($id);
        return view('frontend.news_detail', compact('newsDetail'));
    }
}

resources/views/backend/news/create.blade.php
@extends('backend.layouts.app')
@section('styles')
    <link rel="stylesheet" type="text/css" href="https://jeremyfagis.github.io/dropify/dist/css/dropify.min.css">
@endsection
@section('content')
    <!-- News Header -->
    <div class="page-header row no-gutters py-4">
        <div class="col-12 col-sm-4 text-center text-sm-left mb-0">
            <span class="text-uppercase page-subtitle">News Section</span>
            <h3 class="page-title">Add New News</h3>
        </div>
    </div>
    <!-- End News Header -->
    <form class="add-new-post" action="{{isset($news)?route('news.update', $news):route('news.store')}}" method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-lg-9 col-md-12">
                <!-- Add New Post Form -->
                <div class="card card-small mb-3">
                    <div class="card-body">
                        @csrf
                        @if(isset($news))
                            @method('PATCH')
                        @endif
                        <div class="col-md-12 col-sm-12 p-0 pl-3">
                            <div class="row col-md-12 mb-5">
                                <div class="col-md-4">
                                    <label>News<span class="required">*</span></label>
                                </div>
                                <div class="col-md-7 card p-3">
                                    <input name="image" type="file" class="dropify" data-height="200"
                                           data-default-file="{{isset($news) ? $news->image : ''}}" accept="image/*"/>
                                    @if($errors->first('image'))
                                        <div class="text text-danger">
                                            * {{$errors->first('image')}}
                                        </div>
                                    @endif
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12 col-sm-12 p-0 pl-3">
                            <label>Title <span class="required">*</span> </label>
                            <input class="form-control form-control-lg mb-3" id="title" type="text" name="title" value="{{old('title')?old('title'):(isset($news)?$news->title:'')}}" placeholder="Your News Title">
                            @if($errors->first('title'))
                                <div class="text text-danger">
                                    {{$errors->first('title')}}
                                </div>
                            @endif
                        </div>

                        <div class="col-md-12 col-sm-12 p-0 pl-3">
                            <label>Description</label>
                            @if($errors->first('description'))
                                <div class="text text-danger">
                                    *{{$errors->first('description')}}
                                </div>
                            @endif
                            <textarea id="mytextarea"
                                      name="description">{!! isset($news)?$news->description:(old('description') ?? '') !!}
                        </textarea>
                        </div>

                    </div>
                </div>
                <!-- / Add New Post Form -->
            </div>
            <div class="col-lg-3 col-md-12">
                <!-- Post Overview -->
                <div class='card card-small mb-3'>
                    <div class="card-header border-bottom">
                        <h6 class="m-0">Actions</h6>
                    </div>
                    <div class='card-body p-0'>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item p-3">
                                 <span class="d-flex">
                                    <div class="custom-control">
                                        <input type="hidden" name="status" value="0">
                                        <input type="checkbox" class="custom-control-input" id="customSwitch" name="status"
                                               value="1" {{ (isset($news) && $news->status == 1) || old('status') ? 'checked' : ''}}>
                                        <label class="custom-control-label" for="customSwitch">Is Active</label>
                                    </div>
                                </span>
                            </li>
                            <li class="list-group-item d-flex px-3">
                                    <button type="submit" id="draft" class="btn btn-sm btn-outline-accent" name="status" value="draft">
                                        <i class="material-icons">save</i> Save Draft
                                    </button>
                                    <button type="submit" class="btn btn-sm btn-accent ml-auto">
                                        <i class="material-icons">file_copy</i> Publish
                                    </button>
                            </li>
                        </ul>
                    </div>
                </div>
                <!-- / Post Overview -->
            </div>
        </div>
    </form>
@endsection
@section('js')
    <script type="text/javascript" src="https://jeremyfagis.github.io/dropify/dist/js/dropify.min.js"></script>
    <script>
        $('.dropify').dropify();
    </script>
@endsection

resources/views/backend/news/index.blade.php
@extends('backend.layouts.app')
@section('content')
    <?php

    use Carbon\Carbon; ?>
    <!-- Page Header -->
    <div class="page-header row no-gutters py-4">
        <div class="col-12 col-sm-4 text-center text-sm-left mb-0">
            <!-- <span class="text-uppercase page-subtitle">Overview</span> -->
            <h3 class="page-title">News list</h3>
            <a href="{{route('news.create')}}" class="btn btn-primary mt-4 ml-2"><i class="fa fa-plus"></i> Add New News</a>
        </div>
    </div>
    <!-- End Page Header -->
    <!-- Default Light Table -->
    <div class="row">
        <div class="col">
            <div class="card card-small mb-4">
                <div class="card-body p-3 text-center">
                    <div class="table-responsive p-1">
                        <table id="event-table" class="table table-striped table-bordered" style="width:100%">
                            <thead>
                            <tr>
                                <th>Date</th>
                                <th>Image</th>
                                <th>Title</th>
                                <th>Status</th>
                                <th>Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($newses as $news)
                                <tr>
                                    <td class="font-weight-bold">{{ Carbon::parse($news->created_at)->format('Y M d H:i A')}}
                                    </td>
                                    <td><img src="{{$news->image}}" alt="" height="100px"; width="100px";></td>
                                    <td>{{$news->title}}</td>
                                    <td class="text-center">
                                        @if($news->status==1)
                                            <span class="shadow-none badge badge-success">Active</span>
                                        @else
                                            <span class="shadow-none badge badge-danger">Inactive</span>
                                        @endif
                                    </td>
                                    <td>
                                        <div class="d-flex justify-content-center">
                                            <a class="btn btn-warning btn-sm mr-2" href="{{route('news.edit',$news)}}">Edit</a>
                                            <form action="{{route('news.destroy',$news)}}" method="post" onsubmit="return confirm('Are you sure?')">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" class="btn btn-sm btn-danger mr-2"><i class="fa fa-trash text-white" title="Delete"></i> </button>
                                            </form>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Default Light Table -->
    <script type="text/javascript">
        $(document).ready(function() {
            setTimeout(function() {
                $('.alert .close').click()
            }, 3000);
            $('#event-table').DataTable({
                "columnDefs": [{
                    "width": "100px",
                    "targets": 0
                },
                    {
                        "width": "150px",
                        "targets": 1
                    },
                    {
                        "width": "150px",
                        "targets": 2
                    },
                    {
                        "width": "70px",
                        "targets": 3
                    },
                ],
            });
        });
    </script>
@endsection